/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CompanyApplicationsRouteImport } from './routes/company-applications'
import { Route as CompanyJobsRouteImport } from './routes/company-jobs'
import { Route as CompanyMyJobsRouteImport } from './routes/company-my-jobs'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyApplicationsRoute = CompanyApplicationsRouteImport.update({
  id: '/company-applications',
  path: '/company-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/company-jobs',
  path: '/company-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyMyJobsRoute = CompanyMyJobsRouteImport.update({
  id: '/company-my-jobs',
  path: '/company-my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/company-applications': typeof CompanyApplicationsRoute
  '/company-jobs': typeof CompanyJobsRoute
  '/company-my-jobs': typeof CompanyMyJobsRoute
  '/resume': typeof ResumeRoute
  '/saved': typeof SavedRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/company-applications': typeof CompanyApplicationsRoute
  '/company-jobs': typeof CompanyJobsRoute
  '/company-my-jobs': typeof CompanyMyJobsRoute
  '/resume': typeof ResumeRoute
  '/saved': typeof SavedRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/company-applications': typeof CompanyApplicationsRoute
  '/company-jobs': typeof CompanyJobsRoute
  '/company-my-jobs': typeof CompanyMyJobsRoute
  '/resume': typeof ResumeRoute
  '/saved': typeof SavedRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/assistant'
    | '/auth'
    | '/company'
    | '/company-applications'
    | '/company-jobs'
    | '/company-my-jobs'
    | '/resume'
    | '/saved'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/applications'
    | '/assistant'
    | '/auth'
    | '/company'
    | '/company-applications'
    | '/company-jobs'
    | '/company-my-jobs'
    | '/resume'
    | '/saved'
    | '/jobs/$jobId'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/assistant'
    | '/auth'
    | '/company'
    | '/company-applications'
    | '/company-jobs'
    | '/company-my-jobs'
    | '/resume'
    | '/saved'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CompanyRoute: typeof CompanyRoute
  CompanyApplicationsRoute: typeof CompanyApplicationsRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyMyJobsRoute: typeof CompanyMyJobsRoute
  ResumeRoute: typeof ResumeRoute
  SavedRoute: typeof SavedRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-applications': {
      id: '/company-applications'
      path: '/company-applications'
      fullPath: '/company-applications'
      preLoaderRoute: typeof CompanyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-jobs': {
      id: '/company-jobs'
      path: '/company-jobs'
      fullPath: '/company-jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-my-jobs': {
      id: '/company-my-jobs'
      path: '/company-my-jobs'
      fullPath: '/company-my-jobs'
      preLoaderRoute: typeof CompanyMyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CompanyRoute: CompanyRoute,
  CompanyApplicationsRoute: CompanyApplicationsRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyMyJobsRoute: CompanyMyJobsRoute,
  ResumeRoute: ResumeRoute,
  SavedRoute: SavedRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
